<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <ProjectReference Include="../ObsLiveBot.Domain/ObsLiveBot.Domain.csproj" />
    <ProjectReference Include="../ObsLiveBot.Application/ObsLiveBot.Application.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
